'use client'

import { useEffect, useMemo, useRef, useState, useTransition } from 'react'
import { saveCalendarDayBackground, saveCalendarDaysBulk } from '@/app/(program)/calendars/actions'

type Day = { id: string; date: string; in_session: boolean; notes: string | null; activity_type_ids: string[] }
type Activity = { id: string; code: string; name: string; allowed_when_in_session: boolean; allowed_when_not_in_session: boolean }
type SaveState = 'idle' | 'saving' | 'saved' | 'error'
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
function dateFromIso(value: string) { return new Date(`${value}T00:00:00.000Z`) }
function monthLabel(value: string) { return new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(dateFromIso(value)) }
function shortDate(value: string) { return new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(dateFromIso(value)) }

export function CalendarDayGrid({ calendarId, days, activities, editable = true }: { calendarId: string; days: Day[]; activities: Activity[]; editable?: boolean }) {
  const [localDays, setLocalDays] = useState(days), [selectedId, setSelectedId] = useState<string | null>(null), [activeMonthIndex, setActiveMonthIndex] = useState(0)
  const [bulkMode, setBulkMode] = useState(false), [bulkIds, setBulkIds] = useState<string[]>([]), [rangeAnchor, setRangeAnchor] = useState<string | null>(null)
  const [bulkPanel, setBulkPanel] = useState(false), [bulkInSession, setBulkInSession] = useState(false), [bulkActivities, setBulkActivities] = useState<string[]>([]), [bulkNotes, setBulkNotes] = useState(''), [bulkSaving, setBulkSaving] = useState(false), [bulkError, setBulkError] = useState('')
  const selectedDay = localDays.find((day) => day.id === selectedId) ?? null
  const [inSession, setInSession] = useState(false), [selectedActivities, setSelectedActivities] = useState<string[]>([]), [notes, setNotes] = useState(''), [saveState, setSaveState] = useState<SaveState>('idle'), [saveError, setSaveError] = useState('')
  const [, startTransition] = useTransition(), saveVersion = useRef(0)
  useEffect(() => setLocalDays(days), [days])
  const months = useMemo(() => { const grouped = new Map<string, Day[]>(); for (const day of localDays) { const key = day.date.slice(0, 7); grouped.set(key, [...(grouped.get(key) ?? []), day]) } return [...grouped.entries()] }, [localDays])
  useEffect(() => { if (activeMonthIndex > months.length - 1) setActiveMonthIndex(Math.max(0, months.length - 1)) }, [activeMonthIndex, months.length])
  useEffect(() => { function key(e: KeyboardEvent) { if (e.key === 'Escape') { setSelectedId(null); setBulkPanel(false); if (bulkMode) { setBulkIds([]); setRangeAnchor(null) } } } window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [bulkMode])
  const activeMonth = months[activeMonthIndex], activeMonthDays = activeMonth?.[1] ?? [], activeMonthKey = activeMonth?.[0] ?? ''
  const activeSessionDays = activeMonthDays.filter((day) => day.in_session).length, activeActivityDays = activeMonthDays.filter((day) => day.activity_type_ids.length > 0).length
  const selectedBulkDays = localDays.filter((day) => bulkIds.includes(day.id)).sort((a, b) => a.date.localeCompare(b.date))

  function selectDay(day: Day) { setSelectedId(day.id); setInSession(day.in_session); setSelectedActivities(day.activity_type_ids); setNotes(day.notes ?? ''); setSaveState('idle'); setSaveError('') }
  function toggleBulkDay(day: Day, shiftKey: boolean) {
    if (shiftKey && rangeAnchor) {
      const ordered = localDays.slice().sort((a, b) => a.date.localeCompare(b.date)), a = ordered.findIndex((item) => item.id === rangeAnchor), b = ordered.findIndex((item) => item.id === day.id)
      if (a >= 0 && b >= 0) setBulkIds((current) => [...new Set([...current, ...ordered.slice(Math.min(a, b), Math.max(a, b) + 1).map((item) => item.id)])])
    } else { setBulkIds((current) => current.includes(day.id) ? current.filter((id) => id !== day.id) : [...current, day.id]); setRangeAnchor(day.id) }
  }
  function persist(nextInSession: boolean, nextActivities: string[], nextNotes: string, delay = 0) {
    if (!selectedDay || !editable) return; const dayId = selectedDay.id, version = ++saveVersion.current
    setLocalDays((current) => current.map((day) => day.id === dayId ? { ...day, in_session: nextInSession, activity_type_ids: nextActivities, notes: nextNotes } : day)); setSaveState('saving'); setSaveError('')
    window.setTimeout(() => { if (version !== saveVersion.current) return; startTransition(async () => { const result = await saveCalendarDayBackground({ dayId, calendarId, inSession: nextInSession, activityIds: nextActivities, notes: nextNotes }); if (version !== saveVersion.current) return; if (!result.ok) { setSaveState('error'); setSaveError(result.error); return } setSaveState('saved'); window.setTimeout(() => setSaveState((current) => current === 'saved' ? 'idle' : current), 1600) }) }, delay)
  }
  function changeSession(next: boolean) { const nextActivities = selectedActivities.filter((id) => { const activity = activities.find((item) => item.id === id); return activity ? (next ? activity.allowed_when_in_session : activity.allowed_when_not_in_session) : false }); setInSession(next); setSelectedActivities(nextActivities); persist(next, nextActivities, notes) }
  function toggleActivity(id: string, checked: boolean) { const next = checked ? [...new Set([...selectedActivities, id])] : selectedActivities.filter((item) => item !== id); setSelectedActivities(next); persist(inSession, next, notes) }
  function changeNotes(value: string) { setNotes(value); persist(inSession, selectedActivities, value, 650) }
  function goToMonth(index: number) { setSelectedId(null); setActiveMonthIndex(Math.max(0, Math.min(months.length - 1, index))) }
  function startBulkEdit() { setBulkInSession(false); setBulkActivities([]); setBulkNotes(''); setBulkError(''); setBulkPanel(true) }
  function clearBulk() { setBulkIds([]); setRangeAnchor(null); setBulkPanel(false) }
  async function applyBulk() {
    if (!selectedBulkDays.length) return; setBulkSaving(true); setBulkError('')
    const allowedActivities = bulkActivities.filter((id) => { const activity = activities.find((item) => item.id === id); return activity ? (bulkInSession ? activity.allowed_when_in_session : activity.allowed_when_not_in_session) : false })
    const result = await saveCalendarDaysBulk({ calendarId, days: selectedBulkDays.map((day) => ({ dayId: day.id, inSession: bulkInSession, activityIds: allowedActivities, notes: bulkNotes })) })
    setBulkSaving(false); if (!result.ok) { setBulkError(result.error); return }
    const ids = new Set(bulkIds); setLocalDays((current) => current.map((day) => ids.has(day.id) ? { ...day, in_session: bulkInSession, activity_type_ids: allowedActivities, notes: bulkNotes } : day)); clearBulk()
  }
  if (!activeMonth) return <div className="empty-state">No calendar dates are available.</div>
  const firstWeekday = dateFromIso(`${activeMonthKey}-01`).getUTCDay(), populatedCells = firstWeekday + activeMonthDays.length, trailingCells = (7 - (populatedCells % 7)) % 7, monthTitle = monthLabel(activeMonthDays[0].date)
  return <>
    <section className="calendar-browser" aria-labelledby="calendar-month-heading">
      <div className="calendar-toolbar"><div className="calendar-toolbar-left"><button className="month-arrow" type="button" aria-label="Previous month" disabled={activeMonthIndex === 0} onClick={() => goToMonth(activeMonthIndex - 1)}>‹</button><div className="month-select-wrap"><label className="sr-only" htmlFor="calendar-month-select">Month</label><select id="calendar-month-select" className="month-select" value={activeMonthIndex} onChange={(e) => goToMonth(Number(e.target.value))}>{months.map(([month, monthDays], index) => <option key={month} value={index}>{monthLabel(monthDays[0].date)}</option>)}</select></div><button className="month-arrow" type="button" aria-label="Next month" disabled={activeMonthIndex === months.length - 1} onClick={() => goToMonth(activeMonthIndex + 1)}>›</button></div><div className="calendar-toolbar-summary"><span><strong>{activeSessionDays}</strong> session</span><span><strong>{activeActivityDays}</strong> activity</span></div><button type="button" className={`bulk-mode-button ${bulkMode ? 'bulk-mode-active' : ''}`} disabled={!editable} onClick={() => { setBulkMode((value) => !value); clearBulk() }}>{bulkMode ? 'Done selecting' : 'Select multiple'}</button></div>
      {bulkMode ? <div className="bulk-selection-bar"><div><strong>{bulkIds.length ? `${bulkIds.length} date${bulkIds.length === 1 ? '' : 's'} selected` : 'Select dates'}</strong><span>Click dates individually. Shift-click selects a continuous range, including across months.</span></div><div className="actions-row"><button type="button" className="button button-secondary button-small" disabled={!bulkIds.length} onClick={clearBulk}>Clear</button><button type="button" className="button button-small" disabled={!bulkIds.length} onClick={startBulkEdit}>Edit selected dates</button></div></div> : null}
      <div className="calendar-month-heading-row"><div><p className="calendar-current-eyebrow">Program calendar</p><h2 id="calendar-month-heading" aria-live="polite">{monthTitle}</h2></div><div className="calendar-legend"><span><i className="legend-swatch legend-session" /> In session</span><span><i className="legend-swatch legend-activity" /> Activity</span>{bulkMode ? <span><i className="legend-swatch legend-selected" /> Selected</span> : null}</div></div>
      <div className="professional-calendar" role="grid" aria-label={`${monthTitle} program calendar`}><div className="weekday-header" role="row">{WEEKDAYS.map((label) => <span role="columnheader" key={label}><span className="weekday-long">{label}</span><span className="weekday-short">{label.slice(0, 3)}</span></span>)}</div><div className="month-grid">{Array.from({ length: firstWeekday }).map((_, i) => <span className="calendar-blank" aria-hidden="true" key={`lead-${i}`} />)}{activeMonthDays.map((day) => { const dayActivities = activities.filter((activity) => day.activity_type_ids.includes(activity.id)), isBulkSelected = bulkIds.includes(day.id); return <button type="button" role="gridcell" aria-label={`${shortDate(day.date)}, ${day.in_session ? 'in session' : 'not in session'}`} aria-pressed={bulkMode ? isBulkSelected : selectedId === day.id} key={day.id} className={`calendar-day ${day.in_session ? 'calendar-day-session' : ''} ${selectedId === day.id ? 'calendar-day-selected' : ''} ${isBulkSelected ? 'calendar-day-bulk-selected' : ''}`} onClick={(e) => bulkMode ? toggleBulkDay(day, e.shiftKey) : selectDay(day)}><div className="calendar-day-top"><span className="calendar-day-number">{Number(day.date.slice(8, 10))}</span>{isBulkSelected ? <span className="bulk-check">✓</span> : day.in_session ? <span className="session-dot" aria-hidden="true" /> : null}</div><div className="calendar-day-content"><span className={`day-marker ${day.in_session ? '' : 'day-marker-off'}`}>{day.in_session ? 'In session' : 'No session'}</span>{dayActivities.slice(0, 2).map((activity) => <span className="activity-chip" key={activity.id}>{activity.name}</span>)}{dayActivities.length > 2 ? <span className="day-more">+{dayActivities.length - 2} more</span> : null}{day.notes ? <span className="notes-indicator">● Note</span> : null}</div></button>})}{Array.from({ length: trailingCells }).map((_, i) => <span className="calendar-blank" aria-hidden="true" key={`trail-${i}`} />)}</div></div>
      <div className="calendar-footer-nav"><button className="calendar-text-nav" type="button" disabled={activeMonthIndex === 0} onClick={() => goToMonth(activeMonthIndex - 1)}>← Previous month</button><span>{bulkMode ? 'Selection stays active while you change months' : `Select any date to ${editable ? 'edit' : 'view'} details`}</span><button className="calendar-text-nav" type="button" disabled={activeMonthIndex === months.length - 1} onClick={() => goToMonth(activeMonthIndex + 1)}>Next month →</button></div>
    </section>
    {bulkPanel ? <div className="drawer-backdrop" role="presentation" onMouseDown={() => setBulkPanel(false)}><aside className="day-drawer" role="dialog" aria-modal="true" aria-labelledby="bulk-title" onMouseDown={(e) => e.stopPropagation()}><div className="drawer-header"><div><p className="drawer-eyebrow">Bulk edit</p><h2 id="bulk-title">{selectedBulkDays.length} selected dates</h2><p className="muted small-text bulk-date-range">{selectedBulkDays[0] ? shortDate(selectedBulkDays[0].date) : ''}{selectedBulkDays.length > 1 ? ` – ${shortDate(selectedBulkDays[selectedBulkDays.length - 1].date)}` : ''}</p></div><button className="icon-button" type="button" onClick={() => setBulkPanel(false)} aria-label="Close bulk editor">×</button></div><div className="stack day-editor"><div className="bulk-warning"><strong>This replaces these fields on every selected date.</strong><span>Use this for breaks, closures, conference periods, and other shared calendar changes.</span></div>{bulkError ? <div className="alert alert-error">{bulkError}</div> : null}<fieldset className="fieldset editor-section"><legend>Children in session?</legend><div className="segmented"><label className={bulkInSession ? 'segment-active' : ''}><input type="radio" name="bulk-session" checked={bulkInSession} onChange={() => setBulkInSession(true)} />Yes</label><label className={!bulkInSession ? 'segment-active' : ''}><input type="radio" name="bulk-session" checked={!bulkInSession} onChange={() => setBulkInSession(false)} />No</label></div></fieldset><fieldset className="fieldset editor-section"><legend>Activities</legend><p className="muted small-text">Optional. Choose activities that apply to all selected dates.</p><div className="activity-options">{activities.map((activity) => { const allowed = bulkInSession ? activity.allowed_when_in_session : activity.allowed_when_not_in_session; return <label className={`checkbox-card ${bulkActivities.includes(activity.id) ? 'checkbox-selected' : ''} ${!allowed ? 'checkbox-disabled' : ''}`} key={activity.id}><input type="checkbox" checked={bulkActivities.includes(activity.id)} disabled={!allowed} onChange={(e) => setBulkActivities((current) => e.target.checked ? [...new Set([...current, activity.id])] : current.filter((id) => id !== activity.id))} /><span>{activity.name}</span></label> })}</div></fieldset><div className="field editor-section"><label htmlFor="bulk-notes">Shared note <span className="optional-label">Optional</span></label><textarea id="bulk-notes" rows={3} value={bulkNotes} onChange={(e) => setBulkNotes(e.target.value)} placeholder="Example: Winter break" /></div><button className="button bulk-apply-button" type="button" disabled={bulkSaving} onClick={applyBulk}>{bulkSaving ? 'Applying changes…' : `Apply to ${selectedBulkDays.length} dates`}</button></div></aside></div> : null}
    {selectedDay && !bulkMode ? <div className="drawer-backdrop" role="presentation" onMouseDown={() => setSelectedId(null)}><aside className="day-drawer" role="dialog" aria-modal="true" aria-labelledby="day-drawer-title" onMouseDown={(e) => e.stopPropagation()}><div className="drawer-header"><div><p className="drawer-eyebrow">Calendar day</p><h2 id="day-drawer-title">{shortDate(selectedDay.date)}</h2></div><button className="icon-button" type="button" onClick={() => setSelectedId(null)} aria-label="Close day editor">×</button></div>{editable ? <div className="stack day-editor"><div className={`autosave-status autosave-${saveState}`} aria-live="polite">{saveState === 'saving' ? 'Saving changes…' : saveState === 'saved' ? 'Saved' : saveState === 'error' ? `Not saved: ${saveError}` : 'Changes save automatically'}</div><fieldset className="fieldset editor-section"><legend>Children in session?</legend><div className="segmented"><label className={inSession ? 'segment-active' : ''}><input type="radio" name="drawer-session" checked={inSession} onChange={() => changeSession(true)} />Yes</label><label className={!inSession ? 'segment-active' : ''}><input type="radio" name="drawer-session" checked={!inSession} onChange={() => changeSession(false)} />No</label></div></fieldset><fieldset className="fieldset editor-section"><legend>Activities</legend><p className="muted small-text">Select everything that applies to this date.</p><div className="activity-options">{activities.map((activity) => { const allowed = inSession ? activity.allowed_when_in_session : activity.allowed_when_not_in_session; return <label className={`checkbox-card ${selectedActivities.includes(activity.id) ? 'checkbox-selected' : ''} ${!allowed ? 'checkbox-disabled' : ''}`} key={activity.id}><input type="checkbox" checked={selectedActivities.includes(activity.id)} disabled={!allowed} onChange={(e) => toggleActivity(activity.id, e.target.checked)} /><span>{activity.name}</span></label> })}</div></fieldset><div className="field editor-section"><label htmlFor={`notes-${selectedDay.id}`}>Notes <span className="optional-label">Optional</span></label><textarea id={`notes-${selectedDay.id}`} rows={4} value={notes} onChange={(e) => changeNotes(e.target.value)} /></div></div> : null}</aside></div> : null}
  </>
}
