-- Oakland Schools Calendar
-- Migration 012: populate the official program directory from ProgramNames.csv.
-- Source contains 177 nonblank, case-insensitively unique program names.
-- Safe to rerun: existing names are ignored by the programs case-insensitive unique index.

insert into public.programs (name)
values
  ('A School for Mind and Body Program'),
  ('Academic Adventures'),
  ('Apple Blossom Learning Center'),
  ('Arts & Technology Academy of Pontiac'),
  ('Avondale School District'),
  ('Babes in Toyland'),
  ('Berkley Building Blocks'),
  ('Beth''s Imagination Station'),
  ('Birmingham Schools'),
  ('Bloomfield Hills School District'),
  ('Bloomfield Maples Montessori'),
  ('Bradford Academy'),
  ('Brandon Early Childhood Center'),
  ('Bright Loritos'),
  ('Building Blocks Preschool'),
  ('Butterfly Bunch'),
  ('Caterpillar Corner Childcare Center'),
  ('Children''s Place Montessori'),
  ('Childtime Children''s Center-Farmington Hills'),
  ('Childtime Children''s Center-Northville'),
  ('Childtime Learning Center Troy-Long Lake Rd.'),
  ('Childtime Learning Center-Commerce Twp.'),
  ('Childtime Learning Center-Lathrup Village'),
  ('Childtime Learning Center-Southfield'),
  ('Childtime Learning Center-Troy'),
  ('Circle Time Preschool'),
  ('Clarenceville School District'),
  ('Clarkston Schools Preschool'),
  ('Clawson Early Childhood Center'),
  ('Crescent Academy'),
  ('Dreamy Children''s Center-Dequindre Rd.'),
  ('Dreamy Day Care 3- John R. Rd.'),
  ('Early Childcare Development Center'),
  ('Early Explorers Academy'),
  ('Early Impressions'),
  ('Early Spark Academy'),
  ('English Oaks Montessori Academy and Childcare'),
  ('Everbrook Academy West Bloomfield'),
  ('Everbrook Academy-Novi'),
  ('Everbrook Academy-South Lyon'),
  ('Faith Factory'),
  ('Faith Troy Preschool'),
  ('Faith''s House'),
  ('Farmington Public Schools@ Farmington Early Childhood Center'),
  ('Ferndale Schools - Early Childhood Center'),
  ('For Kids'' Sake Montessori'),
  ('For Little People'),
  ('Four Corners Montessori Academy'),
  ('Gilden Woods-Commerce'),
  ('Gilden Woods-New Hudson'),
  ('Gilden Woods-Troy'),
  ('Green Garden Child Development Center Huntington Woods'),
  ('Green Garden Child Development Center Madison Heights'),
  ('Green Garden Child Development Center- Clawson'),
  ('Hazel Park Schools'),
  ('Heart of a Child Learning Center'),
  ('Heartfelt Impressions Lake Orion'),
  ('Heartfelt Impressions Rochester/ Goodison'),
  ('Heartfelt Impressions-Clarkston'),
  ('Holly Academy'),
  ('Holly Area School District'),
  ('Huron Valley Schools'),
  ('IXL Learning Center New Hudson'),
  ('IXL Learning Center South Lyon'),
  ('IXL Learning Center Troy'),
  ('IXL Learning Center-Berkley'),
  ('IXL Learning Center; Birmingham'),
  ('Journey Early Childhood Center'),
  ('KiddieKlub Rd.-Rochester Rd.'),
  ('KiddieKlub-Crooks Rd.'),
  ('KinderCare Auburn Hills'),
  ('KinderCare Beck Rd.'),
  ('KinderCare Berkley'),
  ('KinderCare Commerce Township'),
  ('KinderCare Coolidge Highway'),
  ('KinderCare Farmington Hills'),
  ('KinderCare Lake Orion'),
  ('KinderCare Middlebelt Rd.'),
  ('KinderCare New Hudson'),
  ('KinderCare Novi'),
  ('KinderCare Rochester Hills'),
  ('KinderCare Rochester Road'),
  ('KinderCare South Lyon'),
  ('KinderCare Squirrel Rd.'),
  ('KinderCare West Bloomfield'),
  ('Lake Orion Community Schools Early Childhood Program'),
  ('Lamphere School District'),
  ('Lamplighters Preschool'),
  ('Laurel Mara Montessori'),
  ('Leapfrog Christian Daycare'),
  ('Learning Grove Academy'),
  ('Learning Rainbow Academy'),
  ('Lightbridge Academy'),
  ('Lighthouse Shores Academy'),
  ('Lil People''s Place'),
  ('Little Blessings Learning House'),
  ('Little Learners'),
  ('Little Seeds Farmington Hills'),
  ('Little Seeds Novi'),
  ('Little Treasures Early Childhood Center'),
  ('Little Treasures Early Childhood Center; Too'),
  ('Lowry Center for Early Childhood Education at Oakland University'),
  ('Madison Early Childhood Center'),
  ('MAG Childcare and Learning Center'),
  ('Major Child Care Academy'),
  ('Minto''s Casa'),
  ('Momentum Academy'),
  ('Montessori Academy of Farmington Hills'),
  ('Montessori Kids Universe'),
  ('Morgan''s Early Learning Center'),
  ('Novi Cooperative Preschool'),
  ('Novi Early Childhood Center'),
  ('Novi Northville Montessori Center'),
  ('Novi Woods Montessori'),
  ('Oak Park Schools at Lessenger Early Childhood'),
  ('Oakland Family Services Day Care'),
  ('OLHSA Pontiac Head Start'),
  ('Oxford Community Schools'),
  ('PACE Academy'),
  ('Paradigm Care & Enrichment Center'),
  ('PEACE Academy@WHRC'),
  ('Primrose School of Novi'),
  ('Rainbow Zone Childcare Center'),
  ('Rochester Community Schools Pre-K'),
  ('Rosebrook Child Development Center'),
  ('Royal Oak Schools'),
  ('Sage Mara Montessori'),
  ('School Bell'),
  ('Scuola Creativa'),
  ('Somerset Academy'),
  ('Somerset Early Childhood Center'),
  ('South Lyon Community Schools'),
  ('South Lyon Cooperative Preschool'),
  ('Southfield Public Schools-Bussey Center'),
  ('St. Joseph Child Care Center'),
  ('St. Paul Lutheran School Royal Oak'),
  ('Steppin Out On Faith Learning Center'),
  ('Stepping Stone Child Development Center'),
  ('Sunrise Child Care Center'),
  ('Teddy Bear''s Playhouse-Commerce'),
  ('Teddy Bear''s Playhouse-Martin Rd.'),
  ('The Breakie Bunch Learning Center'),
  ('The Goddard School Lake Orion'),
  ('The Goddard School of Beverly Hills'),
  ('The Goddard School of Clarkston'),
  ('The Goddard School of Novi 2'),
  ('The Goddard School of Oxford'),
  ('The Goddard School of Rochester'),
  ('The Goddard School Rochester Hills'),
  ('The Joyful Jungle CLC- Troy'),
  ('The Joyful Jungle CLC-Clawson'),
  ('The Joyful Jungle CLC-MH'),
  ('The Learning Experience Clarkston'),
  ('The Learning Experience Farmington Hills'),
  ('The Learning Experience Novi'),
  ('The Learning Experience South Lyon Twp.'),
  ('The Learning Experience South Lyon West (Pontiac Trail)'),
  ('The Learning Experience Wixom'),
  ('The Learning Tree Lyon Twp.'),
  ('The Learning Tree South Lyon'),
  ('Toddler Time Child Care Center'),
  ('Tomorrow''s Stars Educational Center'),
  ('Tots Learning Center and Child Care'),
  ('Totts Learning Center 2'),
  ('Troy School District Preschool'),
  ('Tutor Time Commerce'),
  ('Tutor Time Farmington Hills'),
  ('Tutor Time Walled Lake'),
  ('Tweetle Beetles Childcare Center'),
  ('Victory Learning Center'),
  ('Walled Lake Consolidated Schools'),
  ('Waterford Oaks Preschool and Childcare'),
  ('Waterford School District-Stepanski Early Childhood Center'),
  ('Wee Discover'),
  ('Wee Friends Commerce'),
  ('Wee Friends Highland'),
  ('West Bloomfield School District')
on conflict do nothing;
