-- Oakland Schools GSRP Calendar
-- Migration 019: transactional bulk edits, atomic date-range changes, and
-- structural validation before submission.

-- ---------------------------------------------------------------------------
-- Atomic bulk day save
-- ---------------------------------------------------------------------------
create or replace function public.save_calendar_days_bulk(
  target_calendar_id uuid,
  day_updates jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  target_day_id uuid;
  activity_ids uuid[];
  saved_count integer := 0;
  target_program_id uuid;
  target_status public.calendar_status;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select c.program_id, c.status
    into target_program_id, target_status
  from public.calendars c
  where c.id = target_calendar_id
  for update;

  if target_program_id is null then
    raise exception 'Calendar not found';
  end if;

  if not public.has_program_access(target_program_id) then
    raise exception 'Calendar access denied' using errcode = '42501';
  end if;

  if not public.is_admin() and target_status = 'PENDING' then
    raise exception 'Pending calendars cannot be edited until review is complete';
  end if;

  if jsonb_typeof(day_updates) <> 'array' then
    raise exception 'day_updates must be a JSON array';
  end if;

  if jsonb_array_length(day_updates) = 0 then
    raise exception 'Select at least one calendar day';
  end if;

  if jsonb_array_length(day_updates) > 62 then
    raise exception 'Bulk edits are limited to 62 dates at a time';
  end if;

  if (
    select count(distinct value ->> 'day_id')
    from jsonb_array_elements(day_updates)
  ) <> jsonb_array_length(day_updates) then
    raise exception 'Each calendar day may appear only once in a bulk update';
  end if;

  for item in select value from jsonb_array_elements(day_updates)
  loop
    target_day_id := nullif(item ->> 'day_id', '')::uuid;

    if target_day_id is null or not exists (
      select 1
      from public.calendar_days cd
      where cd.id = target_day_id
        and cd.calendar_id = target_calendar_id
    ) then
      raise exception 'Bulk update contains a day that does not belong to this calendar';
    end if;

    select coalesce(array_agg(distinct activity_value::uuid), '{}'::uuid[])
      into activity_ids
    from jsonb_array_elements_text(coalesce(item -> 'activity_type_ids', '[]'::jsonb)) as activity_value;

    perform public.save_calendar_day(
      target_day_id,
      coalesce((item ->> 'in_session')::boolean, false),
      coalesce(item ->> 'notes', ''),
      activity_ids
    );

    saved_count := saved_count + 1;
  end loop;

  -- An approved calendar changed after approval must return to review.
  if target_status = 'APPROVED' then
    update public.calendars
    set status = 'PENDING',
        approved_by = null,
        approved_at = null,
        review_notes = null,
        submitted_by = auth.uid(),
        submitted_at = now()
    where id = target_calendar_id;
  end if;

  return saved_count;
end;
$$;

revoke all on function public.save_calendar_days_bulk(uuid, jsonb) from public;
grant execute on function public.save_calendar_days_bulk(uuid, jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- Atomic date-range change
-- Existing day edits inside the new range are preserved. Newly introduced dates
-- are generated by the application and inserted in the same transaction.
-- ---------------------------------------------------------------------------
create or replace function public.update_calendar_range_with_days(
  target_calendar_id uuid,
  new_start_date date,
  new_end_date date,
  generated_days jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_program_id uuid;
  target_school_year_id uuid;
  current_status public.calendar_status;
  year_start date;
  year_end date;
  expected_count integer;
  supplied_count integer;
  item jsonb;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select c.program_id, c.school_year_id, c.status
    into target_program_id, target_school_year_id, current_status
  from public.calendars c
  where c.id = target_calendar_id
  for update;

  if target_program_id is null then
    raise exception 'Calendar not found';
  end if;

  if not public.has_program_access(target_program_id) then
    raise exception 'Calendar access denied' using errcode = '42501';
  end if;

  if not public.is_admin() and current_status = 'PENDING' then
    raise exception 'Pending calendars cannot be edited until review is complete';
  end if;

  if new_start_date > new_end_date then
    raise exception 'Calendar start date must be on or before end date';
  end if;

  select sy.start_date, sy.end_date
    into year_start, year_end
  from public.school_years sy
  where sy.id = target_school_year_id;

  if year_start is null or new_start_date < year_start or new_end_date > year_end then
    raise exception 'Calendar dates must fall inside the selected school year';
  end if;

  if jsonb_typeof(generated_days) <> 'array' then
    raise exception 'generated_days must be a JSON array';
  end if;

  expected_count := (new_end_date - new_start_date) + 1;
  supplied_count := jsonb_array_length(generated_days);

  if supplied_count <> expected_count then
    raise exception 'Generated calendar must contain exactly one row for every date in the new range';
  end if;

  if exists (
    select 1
    from generate_series(new_start_date, new_end_date, interval '1 day') expected(day)
    left join lateral (
      select count(*) as matches
      from jsonb_array_elements(generated_days) item_match
      where (item_match ->> 'date')::date = expected.day::date
    ) supplied on true
    where supplied.matches <> 1
  ) then
    raise exception 'Generated calendar dates must exactly cover the new range without duplicates';
  end if;

  delete from public.calendar_days
  where calendar_id = target_calendar_id
    and (date < new_start_date or date > new_end_date);

  for item in select value from jsonb_array_elements(generated_days)
  loop
    insert into public.calendar_days (calendar_id, date, in_session)
    values (
      target_calendar_id,
      (item ->> 'date')::date,
      coalesce((item ->> 'in_session')::boolean, false)
    )
    on conflict (calendar_id, date) do nothing;
  end loop;

  update public.calendars
  set start_date = new_start_date,
      end_date = new_end_date,
      status = case when current_status = 'APPROVED' then 'PENDING' else current_status end,
      approved_by = case when current_status = 'APPROVED' then null else approved_by end,
      approved_at = case when current_status = 'APPROVED' then null else approved_at end,
      review_notes = case when current_status = 'APPROVED' then null else review_notes end,
      submitted_by = case when current_status = 'APPROVED' then auth.uid() else submitted_by end,
      submitted_at = case when current_status = 'APPROVED' then now() else submitted_at end
  where id = target_calendar_id;
end;
$$;

revoke all on function public.update_calendar_range_with_days(uuid, date, date, jsonb) from public;
grant execute on function public.update_calendar_range_with_days(uuid, date, date, jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- Structural validation used by submit/approve.
-- ---------------------------------------------------------------------------
create or replace function public.calendar_has_structural_failures(target_calendar_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_start date;
  target_end date;
  target_school_year_id uuid;
  expected_count integer;
  actual_count integer;
begin
  select c.start_date, c.end_date, c.school_year_id
    into target_start, target_end, target_school_year_id
  from public.calendars c
  where c.id = target_calendar_id;

  if target_start is null then
    raise exception 'Calendar not found';
  end if;

  expected_count := (target_end - target_start) + 1;
  select count(*)::integer into actual_count
  from public.calendar_days cd
  where cd.calendar_id = target_calendar_id;

  if actual_count <> expected_count then
    return true;
  end if;

  if exists (
    select 1
    from generate_series(target_start, target_end, interval '1 day') expected(day)
    where not exists (
      select 1 from public.calendar_days cd
      where cd.calendar_id = target_calendar_id
        and cd.date = expected.day::date
    )
  ) then
    return true;
  end if;

  if exists (
    select 1
    from public.calendar_days cd
    join public.blocked_dates bd
      on bd.school_year_id = target_school_year_id
     and bd.date = cd.date
     and bd.active = true
    where cd.calendar_id = target_calendar_id
      and (
        (bd.restriction_type = 'NO_SESSION' and cd.in_session = true)
        or
        (bd.restriction_type = 'NO_ACTIVITY' and (
          cd.in_session = true
          or exists (
            select 1 from public.calendar_day_activities cda
            where cda.calendar_day_id = cd.id
          )
        ))
      )
  ) then
    return true;
  end if;

  return false;
end;
$$;

revoke all on function public.calendar_has_structural_failures(uuid) from public;
grant execute on function public.calendar_has_structural_failures(uuid) to authenticated;

create or replace function public.submit_calendar(target_calendar_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_program_id uuid;
  current_status public.calendar_status;
begin
  select c.program_id, c.status
    into target_program_id, current_status
  from public.calendars c
  where c.id = target_calendar_id
  for update;

  if target_program_id is null then raise exception 'Calendar not found'; end if;
  if not public.has_program_access(target_program_id) then raise exception 'Calendar access denied' using errcode = '42501'; end if;
  if current_status not in ('DRAFT', 'CHANGES_REQUESTED') then raise exception 'Only draft or changes-requested calendars can be submitted'; end if;
  if public.calendar_has_structural_failures(target_calendar_id) then raise exception 'Calendar contains missing dates or blocked-date conflicts and cannot be submitted'; end if;
  if public.calendar_has_blocking_requirement_failures(target_calendar_id) then raise exception 'Calendar has blocking requirement failures and cannot be submitted'; end if;

  update public.calendars
  set status = 'PENDING', submitted_by = auth.uid(), submitted_at = now(), approved_by = null, approved_at = null, review_notes = null
  where id = target_calendar_id;
end;
$$;

create or replace function public.approve_calendar(target_calendar_id uuid, notes text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_status public.calendar_status;
begin
  if not public.is_admin() then raise exception 'Administrator access required' using errcode = '42501'; end if;
  select c.status into current_status from public.calendars c where c.id = target_calendar_id for update;
  if current_status is null then raise exception 'Calendar not found'; end if;
  if current_status <> 'PENDING' then raise exception 'Only pending calendars can be approved'; end if;
  if public.calendar_has_structural_failures(target_calendar_id) then raise exception 'Calendar contains missing dates or blocked-date conflicts and cannot be approved'; end if;
  if public.calendar_has_blocking_requirement_failures(target_calendar_id) then raise exception 'Calendar has blocking requirement failures and cannot be approved'; end if;

  update public.calendars
  set status = 'APPROVED', approved_by = auth.uid(), approved_at = now(), review_notes = nullif(btrim(notes), '')
  where id = target_calendar_id;
end;
$$;
